"""empty message

Revision ID: 3b9512b75ae4
Revises: 1666b1c5eb9b
Create Date: 2020-08-03 13:20:48.988689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9512b75ae4'
down_revision = '1666b1c5eb9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('imdb_rating', sa.String(length=50), nullable=False))
    op.add_column('movies', sa.Column('poster', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'poster')
    op.drop_column('movies', 'imdb_rating')
    # ### end Alembic commands ###
